# Generated by Django 2.2.4 on 2019-08-20 12:32

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190820_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=('title',), unique=True),
        ),
    ]
